apiVersion: v1
kind: Endpoints
metadata:
  name: {{ include "external-ingress.serviceName" . }}
  labels:
    {{- include "external-ingress.labels" . | nindent 4 }}
subsets:
- addresses:
  - ip: {{ .Values.internalip }}
  ports:
  - name: {{ include "external-ingress.fullname" . }}-port
    port: {{ .Values.internalport | int }}
    protocol: TCP
