apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .Chart.Name }}-service
  labels:
    app: {{ .Chart.Name }}
subsets:
- addresses:
  - ip: {{ .Values.internalip }}
  ports:
  - name: {{ .Chart.Name }}-port
    port: {{ .Values.internalport }}
    protocol: TCP
