{{- range .Values.extraIngresses }}
{{- $extra := . }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "external-ingress.fullname" $ }}-ingress-{{ $extra.name }}
  annotations:
    {{- with $extra.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "external-ingress.labels" $ | nindent 4 }}
spec:
  {{- if and $.Values.ingress.tls $.Values.ingress.tls.enabled }}
  tls:
    {{- range $.Values.ingress.hosts }}
    - hosts:
        - {{ .url }}
      secretName: {{ replace "." "-" (printf "%s--%s" .url "tls-secret") }}
    {{- end }}
  {{- end }}
  ingressClassName: {{ $.Values.ingress.className }}
  rules:
    {{- range $.Values.ingress.hosts }}
    - host: {{ .url }}
      http:
        paths:
        - path: {{ $extra.path }}
          pathType: ImplementationSpecific
          backend:
            service:
              name: {{ include "external-ingress.serviceName" $ }}
              port:
                number: {{ $.Values.internalport | int }}
    {{- end }}
---
{{- end }}
