apiVersion: v1
kind: Service
metadata:
  name: {{ include "external-ingress.serviceName" . }}
  labels:
    {{- include "external-ingress.labels" . | nindent 4 }}
spec:
  ports:
  - name: {{ include "external-ingress.fullname" . }}-port
    port: {{ .Values.internalport | int }}
    protocol: TCP
    targetPort: {{ .Values.internalport | int }}
