apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "odoo-doodba.fullname" . }}
  labels:
{{ include "odoo-doodba.labels" . | indent 4 }}
data:
  {{- if .Values.config }}
  k8s_configmap.conf: {{ tpl (toYaml .Values.config) $ | indent 2 }}
  {{- end }}
  # Extra Configuration
  {{- if .Values.odoo.config }}
  {{- toYaml .Values.odoo.config | nindent 4 }}
  {{- end }}