apiVersion: v1
kind: Secret
metadata:
  name: {{ include "odoo-doodba.fullname" . }}
  labels:
{{ include "odoo-doodba.labels" . | indent 4 }}
type: Opaque
data:
  odoo-password:
    {{ if .Values.odooPassword }}
      {{ .Values.odooPassword |  b64enc | quote }}
    {{ else if ((.Values.config).ADMIN_PASSWORD) }}
        {{ .Values.config.ADMIN_PASSWORD |  b64enc | quote  }}
    {{ else }}
        {{ randAlphaNum 10 |  b64enc | quote }}
    {{ end }}
  postgresql-password:
    {{ if not .Values.postgresql.enabled }}
     {{ if .Values.postgresql.postgresqlPassword}}
        {{ .Values.postgresql.postgresqlPassword |  b64enc | quote  }}
      {{ else if ((.Values.config).PGPASSWORD) }}
        {{ .Values.config.PGPASSWORD |  b64enc | quote  }}
     {{ else }}
        {{ randAlphaNum 10 |  b64enc | quote }}
     {{ end }}
   {{ end }}
