{{- if .Values.multiplePods.enabled }}
{{- if .Values.multiplePods.xmlrpc.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "odoo.fullname" . }}-xmlrpc
  labels:
    {{- include "odoo.labels" . | nindent 4 }}
    component: xmlrpc
spec:
  replicas: {{ .Values.multiplePods.xmlrpc.replicas }}
  strategy:
    {{- toYaml .Values.updateStrategy | nindent 4 }}
  selector:
    matchLabels:
      {{- include "odoo.selectorLabels" . | nindent 6 }}
      component: xmlrpc
  template:
    metadata:
      labels:
        {{- include "odoo.selectorLabels" . | nindent 8 }}
        component: xmlrpc
      annotations:
        {{- if .Values.customStartScript.enabled }}
        checksum/custom-init-script: "{{ .Values.customStartScript.script | toYaml | sha256sum }}"
        {{- end }}
        checksum/environment: "{{ .Values.config | toYaml | sha256sum }}"
    spec:
      {{- if .Values.imagePullSecret.existingSecret }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret.existingSecret | quote }}
      {{- else if and .Values.imagePullSecret.user .Values.imagePullSecret.password }}
      imagePullSecrets:
        - name: {{ printf "%s-%s" (sha256sum (printf "%s%s" .Values.imagePullSecret.user .Values.imagePullSecret.password) | substr 0 16) .Release.Name | quote }}
      {{- end }}
      {{- if .Values.persistence.enabled }}
      {{- if .Values.persistence.initVolume }}
      initContainers:
        - name: volume-init
          image: busybox
          command: ['sh', '-c', 'chown 1000:1000 - R /odoo']
          resources:
            requests:
              cpu: "50m"
              memory: "100Mi"
            limits:
              cpu: "100m"
              memory: "200Mi"
          volumeMounts:
            - name: odoo
              mountPath: /odoo
      {{- end }}
      {{- end }}
      containers:
        - name: {{ include "odoo.fullname" . }}-xmlrpc-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.securityContext }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- end }}
          {{- if .Values.customStartScript.enabled }}
          command:
            - {{ .Values.customStartScript.command }}
            - /init-script-path/custom-init-script
          {{- else }}
          command: 
            - "/bin/bash"
          args:
            - "-c"
            - |
              sleep 30
              /opt/odoo/common/entrypoint /usr/local/bin/odoo --xmlrpc-interface=0.0.0.0 --xmlrpc-port=8070 --workers=2
          {{- end }}
          ports:
            - containerPort: 8070
              name: xmlrpc
          resources:
            {{- if .Values.performanceLimit.enabled }}
            requests:
              memory: "{{ .Values.performanceLimit.memory.request }}"
              cpu: "{{ .Values.performanceLimit.cpuTime.request }}"
            limits:
              memory: "{{ .Values.performanceLimit.memory.max }}"
              cpu: "{{ .Values.performanceLimit.cpuTime.max }}"
            {{- else }}
            {{- toYaml .Values.multiplePods.xmlrpc.resources | nindent 14 }}
            {{- end }}
          envFrom:
            - secretRef:
                name: {{ include "odoo.fullname" . }}-environment
          {{- if .Values.extraEnvFrom }}
          {{- toYaml .Values.extraEnvFrom | nindent 12 }}
          {{- end }}
          env:
            {{- range $key, $value := .Values.multiplePods.xmlrpc.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          volumeMounts:
            {{- if .Values.persistence.enabled }}
            - name: odoo
              mountPath: /var/lib/odoo
            {{- end }}
            {{- if .Values.customStartScript.enabled }}
            - name: init-script-volume
              mountPath: /init-script-path
            {{- end }}
      volumes:
        {{- if .Values.persistence.enabled }}
        - name: odoo
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-odoo-multiple-pods-pvc
        {{- end }}
        {{- if .Values.customStartScript.enabled }}
        - name: init-script-volume
          configMap:
            name: {{ .Release.Name }}-custom-start-script
        {{- end }}
      {{- if .Values.nodeSelector }}
      {{- if .Values.nodeSelector.enabled }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: {{ .Values.nodeSelector.labelname }}
                    operator: In
                    values:
                      - "{{ .Values.nodeSelector.labelvalue }}"
      {{- end }}
      {{- end }}
{{- end }}
{{- end }}