apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" (sha256sum (printf "%s%s" .Values.imagePullSecret.user .Values.imagePullSecret.password) | substr 0 16) .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    app.kubernetes.io/name: {{ include "odoo.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\": {\"%s\": {\"username\": \"%s\", \"password\": \"%s\", \"auth\": \"%s\"}}}" .Values.imagePullSecret.server .Values.imagePullSecret.user .Values.imagePullSecret.password (printf "%s:%s" .Values.imagePullSecret.user .Values.imagePullSecret.password | b64enc ) | b64enc }}

