{{- if and .Values.multiplePods.enabled .Values.multiplePods.webReplicas.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web-replicas-service
  labels:
    {{- include "odoo.labels" . | nindent 4 }}
    component: web-replicas
spec:
  type: ClusterIP
  ports:
    {{- range .Values.ingress.ports }}
    - name: {{ .name }}
      port: {{ .number }}
      targetPort: {{ .number }}
    {{- end }}
  selector:
    component: web-replicas
    app.kubernetes.io/name: {{ include "odoo.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
