{{- if .Values.multiplePods.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web-service
  labels:
    {{- include "odoo.labels" . | nindent 4 }}
    component: web
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
    {{- range .Values.ingress.ports }}
    - name: {{ .name }}
      port: {{ .number }}
      targetPort: {{ .number }}
    {{- end }}
  selector:
    component: web
    app.kubernetes.io/name: {{ include "odoo.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
