apiVersion: v2
name: external-ingress
description: Nginx ingress proxy to a service running in another cluster via internal IP
version: 1.0.1
appVersion: "1.0.0"
maintainers:
  - name: KMEE
    email: contato@kmee.com.br
