{{- if .Values.ingress.enabled }}
{{- range .Values.ingress.extraIngresses }}
{{- $extra := . }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $.Release.Name }}-ingress-{{ $extra.name }}
  annotations:
    checksum/ingress-extra: "{{ $extra | toYaml | sha256sum }}"
    {{- with $extra.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ $.Values.ingress.className | quote }}
  rules:
    {{- range $.Values.ingress.domains }}
    - host: {{ .url | quote }}
      http:
        paths:
          - backend:
              service:
                name: {{ $.Release.Name }}-service
                port:
                  number: {{ $extra.port }}
            path: {{ $extra.path | quote }}
            pathType: ImplementationSpecific
    {{- end }}
  {{- if $.Values.ingress.tls.enabled }}
  tls:
    {{- range $.Values.ingress.domains }}
    - hosts:
        - {{ .url }}
      secretName: {{ default ( replace "." "-" (printf "%s--%s" .url "tls-secret")) .secretName }}
    {{- end }}
  {{- end }}
---
{{- end }}
{{- end }}
