{{- if and .Values.ingress.enabled (eq (default "ingress" .Values.ingress.type) "gateway-api") .Values.ingress.gatewayApi.createGateway }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.ingress.gatewayApi.gatewayName }}
  namespace: {{ .Values.ingress.gatewayApi.gatewayNamespace }}
  labels:
    {{- include "fastapi-app.labels" . | nindent 4 }}
  {{- with .Values.ingress.gatewayApi.gatewayAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  gatewayClassName: {{ default "nginx" .Values.ingress.gatewayApi.gatewayClassName }}
  listeners:
    - name: {{ .Values.ingress.gatewayApi.listenerName }}
      protocol: HTTP
      port: {{ .Values.ingress.gatewayApi.listenerPort }}
      allowedRoutes:
        namespaces:
          from: All
    {{- if .Values.ingress.tls }}
    - name: https
      protocol: HTTPS
      port: 443
      tls:
        mode: Terminate
        certificateRefs:
        {{- /* sem namespace = mesmo namespace do Gateway (não exige ReferenceGrant) */}}
        {{- range .Values.ingress.tls }}
          - name: {{ .secretName }}
            {{- with $.Values.ingress.gatewayApi.certificateNamespace }}
            namespace: {{ . }}
            {{- end }}
        {{- end }}
      allowedRoutes:
        namespaces:
          from: All
    {{- end }}
{{- end }}
